import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  // 产品结构工程师知识库侧边栏
  productStructureSidebar: [{type: 'autogenerated', dirName: 'product-structure'}],
  financeSidebar: [{type: 'autogenerated', dirName: 'finance-freedom'}],
  timeSidebar: [{type: 'autogenerated', dirName: 'time-management'}],
  aiSidebar: [{type: 'autogenerated', dirName: 'ai-applications'}],
};

export default sidebars;
