import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 产品结构工程师知识库侧边栏
  productStructureSidebar: [
    'product-structure/intro',
    {
      type: 'category',
      label: '📚 基础理论',
      items: [
        'product-structure/基础概念',
        'product-structure/材料选择',
      ],
    },
    {
      type: 'category',
      label: '🛠️ 设计方法',
      items: [
        'product-structure/DFM设计',
        'product-structure/公差分析',
      ],
    },
    {
      type: 'category',
      label: '⚙️ 工艺制造',
      items: [
        'product-structure/模具设计',
      ],
    },
    {
      type: 'category',
      label: '✅ 质量验证',
      items: [
        'product-structure/可靠性测试',
      ],
    },
  ],
  financeSidebar: [{type: 'autogenerated', dirName: 'finance-freedom'}],
  timeSidebar: [{type: 'autogenerated', dirName: 'time-management'}],
  aiSidebar: [{type: 'autogenerated', dirName: 'ai-applications'}],
};

export default sidebars;
